[tox]
envlist =
    {py39}-{django42}
    {py310}-{django42,django50,django51}
    {py311}-{django42,django50,django51}
    {py312}-{django42,django50,django51,djangomain}
    {py313}-{django42,django50,django51,djangomain}

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -r{toxinidir}/requirements/local.txt
    django42: django>=4.2,<5.0
    django50: django>=5.0,<5.1
    django51: django>=5.1,<5.2
    djangomain: https://github.com/django/django/archive/main.tar.gz
commands =
    pytest --cov=django_apscheduler --cov-report=xml